plugins {
    id 'java'
    id 'java-library'
}

allprojects {
    group = 'com.neonac'
    version = project.findProperty('NeonACVersion') ?: '1.0.0'

    repositories {
        mavenCentral()
        maven { url = 'https://repo.papermc.io/repository/maven-public/' }
        maven { url = 'https://oss.sonatype.org/content/repositories/snapshots' }
    }
}

subprojects {
    apply plugin: 'java-library'

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(21)
        }
    }

    tasks.withType(JavaCompile).configureEach {
        options.encoding = 'UTF-8'
        options.release = 21
    }

    dependencies {
        testImplementation 'org.junit.jupiter:junit-jupiter:5.10.2'
        testImplementation 'org.mockito:mockito-core:5.11.0'
        testImplementation 'org.mockito:mockito-inline:5.2.0'
        testRuntimeOnly 'org.junit.platform:junit-platform-launcher:1.10.2'
    }

    test {
        useJUnitPlatform()
    }
}
