plugins {
    id 'com.gradleup.shadow' version '8.3.5'
}

dependencies {
    api project(':neonac-api')
    implementation project(':neonac-storage')
    compileOnly 'io.papermc.paper:paper-api:1.21-R0.1-SNAPSHOT'

    testImplementation 'io.papermc.paper:paper-api:1.21-R0.1-SNAPSHOT'
}

shadowJar {
    archiveClassifier.set('')
    archiveBaseName.set('NeonAC')
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE

    from(project(':neonac-checks').sourceSets.main.output)
    from(project(':neonac-versions').sourceSets.main.output)
    from(project(':neonac-checks').sourceSets.main.resources)
}

build.dependsOn shadowJar
